import React,{useEffect,useRef,useState} from "react";
const API="http://localhost:8787/api";
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function speak(text){if(!("speechSynthesis" in window)||!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-IN";u.rate=.95;const v=speechSynthesis.getVoices();u.voice=v.find(x=>x.lang==="en-IN")||v.find(x=>x.lang?.startsWith("en"))||null;speechSynthesis.speak(u)}
export default function App(){
 const [form,setForm]=useState({name:"",role:"Software Engineer",profile:""}),[sessionId,setSessionId]=useState(""),[turn,setTurn]=useState(null),[answer,setAnswer]=useState(""),[status,setStatus]=useState("Ready"),[listening,setListening]=useState(false),[history,setHistory]=useState([]),[error,setError]=useState("");
 const recognition=useRef(null),silenceTimer=useRef(null),lastSpeech=useRef(Date.now()),answerRef=useRef("");
 useEffect(()=>{answerRef.current=answer},[answer]);
 useEffect(()=>{if(!SpeechRecognition)return;const r=new SpeechRecognition();r.lang="en-IN";r.continuous=true;r.interimResults=true;r.maxAlternatives=3;
 r.onresult=e=>{let f="",i="";for(let n=e.resultIndex;n<e.results.length;n++){const t=e.results[n][0].transcript;if(e.results[n].isFinal)f+=t+" ";else i+=t}if(f||i){lastSpeech.current=Date.now();if(f)setAnswer(p=>(p+" "+f).trim());setStatus(i?"Hearing: "+i:"Listening…")}};
 r.onerror=e=>{setError("Speech recognition: "+e.error);setListening(false)};r.onend=()=>setListening(false);recognition.current=r;return()=>{try{r.stop()}catch{}clearInterval(silenceTimer.current)}},[]);
 async function start(){setError("");setStatus("Planning adaptive interview…");try{const res=await fetch(API+"/interview/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await res.json();if(!res.ok)throw new Error(d.error);setSessionId(d.sessionId);setTurn(d.next);setHistory([]);setStatus("Interview started");speak(d.next.question)}catch(e){setError(e.message);setStatus("Could not start")}}
 function beginListening(){if(!recognition.current){setError("SpeechRecognition is unavailable. Use current Chrome/Edge or type the answer.");return}setError("");setAnswer("");lastSpeech.current=Date.now();setListening(true);setStatus("Listening — Indian English (en-IN)");try{recognition.current.start()}catch{}clearInterval(silenceTimer.current);silenceTimer.current=setInterval(()=>{if(Date.now()-lastSpeech.current>1400&&answerRef.current.trim()){try{recognition.current.stop()}catch{}clearInterval(silenceTimer.current)}},300)}
 function stopListening(){try{recognition.current?.stop()}catch{}clearInterval(silenceTimer.current);setListening(false);setStatus("Turn captured")}
 async function submit(){if(!answer.trim()||!sessionId)return;stopListening();setError("");setStatus("Evaluator + controller are reasoning…");const q=turn?.question;try{const res=await fetch(API+"/interview/turn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,answer})});const d=await res.json();if(!res.ok)throw new Error(d.error);setHistory(h=>[...h,{question:q,answer,decision:d.next}]);setTurn(d.next);setAnswer("");setStatus(d.next.action==="finish"?"Interview complete":"Next question generated dynamically");speak(d.next.question)}catch(e){setError(e.message);setStatus("Turn failed")}}
 if(!sessionId)return <main className="shell"><header><div className="brand">NAIN<span>AI</span></div><div className="pill">Dynamic Interview POC</div></header><section className="hero"><p className="eyebrow">VOICE-FIRST · ADAPTIVE · EVIDENCE-BASED</p><h1>An interviewer that actually <em>listens.</em></h1><p>Every next question is generated from what the candidate just said — not from a scripted question bank.</p></section><section className="setup card"><h2>Candidate setup</h2><div className="grid"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Candidate name"/></label><label>Role<input value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/></label></div><label>Resume / profile<textarea rows="9" value={form.profile} onChange={e=>setForm({...form,profile:e.target.value})} placeholder="Paste resume, projects, skills, job description or candidate context…"/></label>{error&&<div className="error">{error}</div>}<button className="primary" onClick={start}>Start adaptive interview →</button></section></main>;
 return <main className="shell"><header><div className="brand">NAIN<span>AI</span></div><div className="live"><i/> LIVE INTERVIEW</div></header><div className="interviewGrid"><section className="card interview"><div className="meta"><span>Competency · {turn?.competency}</span><span>Difficulty {turn?.difficulty}/5</span></div><p className="eyebrow">AI INTERVIEWER</p><h2 className="question">{turn?.question}</h2><div className={"orb "+(listening?"active":"")}><div/><div/><div/></div><div className="status">{status}</div><textarea className="answer" rows="6" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Transcript appears here. You can type for demo/testing."/><div className="actions"><button className={listening?"danger":"secondary"} onClick={listening?stopListening:beginListening}>{listening?"■ Stop":"● Answer by voice"}</button><button className="primary" disabled={!answer.trim()||turn?.action==="finish"} onClick={submit}>Submit answer →</button></div>{error&&<div className="error">{error}</div>}</section><aside className="card trace"><p className="eyebrow">AGENT TRACE</p><h3>Why this question?</h3><p>{turn?.analysis||"Initial question selected from candidate context."}</p><div className="decision"><small>NEXT ACTION</small><strong>{turn?.action?.replaceAll("_"," ").toUpperCase()}</strong></div><h3>Detected topics</h3><div className="chips">{turn?.topics?.length?turn.topics.map(x=><span key={x}>{x}</span>):<span>Awaiting evidence</span>}</div><h3>Evidence</h3><ul>{turn?.evidence?.length?turn.evidence.map((x,i)=><li key={i}>{x}</li>):<li>Interview just started.</li>}</ul><h3>Missing evidence</h3><ul>{turn?.missing_evidence?.map((x,i)=><li key={i}>{x}</li>)}</ul>{turn?.contradictions?.length>0&&<><h3>Needs clarification</h3><ul>{turn.contradictions.map((x,i)=><li key={i}>{x}</li>)}</ul></>}</aside></div>{history.length>0&&<section className="timeline"><p className="eyebrow">INTERVIEW EVIDENCE TRAIL</p>{history.map((h,i)=><details key={i}><summary>Turn {i+1} · {h.decision.action.replaceAll("_"," ")}</summary><b>Q:</b> {h.question}<br/><b>A:</b> {h.answer}</details>)}</section>}</main>
}